language: elixir
elixir:
  - 1.12.3
otp_release:
  - 24.0.2
services:
  - postgresql
env:
  - MIX_ENV=test
before_script:
  # create .env file on Travis-CI:
  - echo "export MIX_ENV=test" > .env
  - mix ecto.setup
script:
  - mix do deps.get, coveralls.json
# See: github.com/dwyl/repo-badges#documentation
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
  - _build
  - deps
